import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar/navbar";
import { FinanceProvider } from "@/context/FinanceContext";

const inter = Inter({ subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
 })

export const metadata: Metadata = {
  title: "Welcome to KoinX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <FinanceProvider>
            {children}
          </FinanceProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
